category:
  path: "/category"
  controller: App\Controller\CategoryController::index

song:
  path: "/song"
  controller: App\Controller\SongController::index

favorite:
  path: "/favorite"
  controller: App\Controller\FavoriteController::index

user:
  path: "/user"
  controller: App\Controller\UserController::index

get_songs_by_category:
  path: "/get-songs-by-category"
  controller: App\Controller\SongController::getSongsByCategory
  methods: ["POST"]

player:
  path: /player/{id}
  controller: App\Controller\PlayerController::showSong
  requirements:
    id: \d+

# admin:
#   path: "/admin"
#   controller: App\Controller\AdminController::index

form_add_category:
  path: "/category/new"
  controller: App\Controller\AdminController::new