category:
  path: "/category"
  controller: App\Controller\CategoryController::index

song:
  path: "/song"
  controller: App\Controller\SongController::index

favorite:
  path: "/favorite"
  controller: App\Controller\FavoriteController::index

  user :
  path: "/user"
  controller: App\Controller\UserController::index
